# Generated by Django 6.1.1 on 2026-10-02 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_factura'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=300)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fecha', models.DateField()),
                ('archivo', models.FileField(upload_to='gastos/')),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='CuentaCobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=300)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fecha', models.DateField()),
                ('archivo', models.FileField(upload_to='cuentas/')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentas', to='core.cliente')),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.contrato')),
            ],
            options={
                'verbose_name_plural': 'Cuentas de cobro',
                'ordering': ['-fecha'],
            },
        ),
    ]
