# Generated by Django 6.1.1 on 2026-10-03 05:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_gasto_cuentacobro'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono_pais',
            field=models.CharField(choices=[('CO', 'Colombia (+57)'), ('US', 'Estados Unidos (+1)'), ('MX', 'México (+52)'), ('ES', 'España (+34)'), ('AR', 'Argentina (+54)'), ('CL', 'Chile (+56)'), ('PE', 'Perú (+51)'), ('BR', 'Brasil (+55)'), ('PA', 'Panamá (+507)'), ('EC', 'Ecuador (+593)'), ('VE', 'Venezuela (+58)'), ('Otro', 'Otro')], default='CO', max_length=10, verbose_name='País del teléfono'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_persona',
            field=models.CharField(choices=[('natural', 'Persona Natural'), ('juridica', 'Persona Jurídica')], default='juridica', max_length=20),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator('^\\d+$', 'El teléfono solo debe contener números.')]),
        ),
    ]
