# Generated by Django 6.1.1 on 2026-10-03 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cliente_fecha_nacimiento_cliente_telefono_pais_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='concepto',
            field=models.CharField(blank=True, max_length=200, verbose_name='Concepto'),
        ),
    ]
