# Generated by Django 6.1.1 on 2026-10-03 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_gasto_concepto'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentacobro',
            name='moneda',
            field=models.CharField(choices=[('COP', 'COP'), ('USD', 'USD'), ('EUR', 'EUR')], default='COP', max_length=3),
        ),
        migrations.AddField(
            model_name='factura',
            name='moneda',
            field=models.CharField(choices=[('COP', 'COP'), ('USD', 'USD'), ('EUR', 'EUR')], default='COP', max_length=3),
        ),
        migrations.AddField(
            model_name='gasto',
            name='moneda',
            field=models.CharField(choices=[('COP', 'COP'), ('USD', 'USD'), ('EUR', 'EUR')], default='COP', max_length=3),
        ),
    ]
