# Generated by Django 6.1.1 on 2026-10-03 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_cuentacobro_moneda_factura_moneda_gasto_moneda'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='pago_verificado_fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='tasa_cop',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='valor_cop',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
    ]
