# Generated by Django 6.1.1 on 2026-10-03 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_factura_pago_verificado_fecha_factura_tasa_cop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentacobro',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='cuentas/'),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='gastos/'),
        ),
    ]
